language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - PLUGIN_NAME=Migrations
    - REQUIRE=""
  matrix:
    - DB=mysql CAKE_VERSION=2.3.10
    - DB=pgsql CAKE_VERSION=2.3.10
    - DB=mysql CAKE_VERSION=2.4.10
    - DB=pgsql CAKE_VERSION=2.4.10
    - DB=mysql CAKE_VERSION=2.5.8
    - DB=pgsql CAKE_VERSION=2.5.8
    - DB=mysql CAKE_VERSION=2.6.4
    - DB=pgsql CAKE_VERSION=2.6.4

matrix:
  include:
    - php: 5.4
      env:
        - COVERALL=1
    - php: 5.4
      env:
        - PHPCS=1

before_script:
  - git clone -b master https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  irc: irc.freenode.org#wasabi
  email: false
  slack:
    secure: QMWzCAOBt69kNN5rFKltkOG26/u5uYtIo0xO1ecowtiMofPeaaNGkrdlP2aaOun5Qg7q0/tTCe7CLp0l4xPulPDOOpqrc3GDosJImgkn7n6/QqzGMr4pUgxe454STDm++H/XbYf7tS6AUTNJjbhIu19+5AX++Xm1DeogDH21VXo=
